var PowerOutageMaps = {
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "Name": "Con Edison of New York", "Description": "<div dir=\"ltr\">Con Edison of New York Power Status Map<span style=\"font-size:10pt\">&nbsp;<\/span><\/div> <a href=\"http:\/\/apps.coned.com\/stormcenter_external\/default.html\" target=\"_blank\">http:\/\/apps.coned.com\/stormcenter_external\/default.html<\/a>" }, "geometry": { "type": "Point", "coordinates": [ -73.806152, 40.925964, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Pepco", "Description": "<div dir=\"ltr\">Pepco Power Status Map<br>&nbsp;<\/div> <a href=\"http:\/\/www.pepco.com\/home\/emergency\/maps\/stormcenter\/\" target=\"_blank\">http:\/\/www.pepco.com\/home\/emergency\/maps\/stormcenter\/<\/a>" }, "geometry": { "type": "Point", "coordinates": [ -76.832886, 38.719807, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Progress Energy", "Description": "<div dir=\"ltr\">Progress Energy Power Status Map<br><a href=\"https:\/\/www.progress-energy.com\/app\/outagemaps\/carolinas.aspx\" target=\"_blank\">https:\/\/www.progress-energy.com\/app\/outagemaps\/carolinas.aspx<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -78.442383, 34.939983, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Delmarva", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\">Delmarva Power Status Map:<\/span><\/div><div dir=\"ltr\"><a href=\"http:\/\/www.delmarva.com\/home\/emergency\/maps\/stormcenter\/\" style=\"font-size:10pt\" target=\"_blank\">http:\/\/www.delmarva.com\/home\/emergency\/maps\/stormcenter\/<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -75.632629, 38.649052, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Atlantic City Electric", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\"><br><\/span><\/div><div dir=\"ltr\"><span style=\"font-size:10pt\">Atlantic City Electric Power Status Map:&nbsp;<\/span><\/div> <a href=\"http:\/\/www.atlanticcityelectric.com\/home\/emergency\/maps\/stormcenter\/\" target=\"_blank\">http:\/\/www.atlanticcityelectric.com\/home\/emergency\/maps\/stormcenter\/<\/a>" }, "geometry": { "type": "Point", "coordinates": [ -74.432373, 39.368279, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Long Island Power Authority", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\">Long Island Power Authority Power Status Map:<\/span><\/div><div dir=\"ltr\"><a href=\"http:\/\/www.lipower.org\/stormcenter\/outagemap.html\" style=\"font-size:10pt\" target=\"_blank\">http:\/\/www.lipower.org\/stormcenter\/outagemap.html<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -73.234863, 40.780540, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Vermont Electric Cooperative", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\">Vermont Electric Cooperative Power Status:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div> <a href=\"http:\/\/www.vermontelectric.coop\/outage\" target=\"_blank\">http:\/\/www.vermontelectric.coop\/outage<\/a>" }, "geometry": { "type": "Point", "coordinates": [ -72.883301, 43.484814, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Green Mountain Power", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\">Green Mountain Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div> <a href=\"https:\/\/wss.greenmountainpower.com\/customers\/outages\/\" target=\"_blank\">https:\/\/wss.greenmountainpower.com\/customers\/outages\/<\/a>" }, "geometry": { "type": "Point", "coordinates": [ -72.853088, 42.819580, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "PECO", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\">PECO Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div> <a href=\"https:\/\/www.peco.com\/CustomerService\/OutageCenter\/OutageMap\/Pages\/OutageMap.aspx\" target=\"_blank\">https:\/\/www.peco.com\/CustomerService\/OutageCenter\/OutageMap\/Pages\/OutageMap.aspx<\/a>" }, "geometry": { "type": "Point", "coordinates": [ -75.355225, 40.014996, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Jersey Central", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\">Jersey Central Power &amp; Light Power Status Map:&nbsp;<\/span><\/div> <a href=\"http:\/\/outages.firstenergycorp.com\/nj.html\" target=\"_blank\">http:\/\/outages.firstenergycorp.com\/nj.html<\/a>" }, "geometry": { "type": "Point", "coordinates": [ -74.487305, 40.245991, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "NYSEG", "Description": "<div><span style=\"font-size:10pt\">NYSEG Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div><div><a href=\"http:\/\/outagemap.nyseg.com\/ny\/?style=newyork\" target=\"_blank\">http:\/\/outagemap.nyseg.com\/ny\/?style=newyork<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -75.300293, 42.585445, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "PennPower", "Description": "<div><span style=\"font-size:10pt\">PennPower Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div><div><a href=\"http:\/\/outages.firstenergycorp.com\/pa.html\" target=\"_blank\">http:\/\/outages.firstenergycorp.com\/pa.html<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -77.211914, 40.346542, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Connecticut Light and Power", "Description": "<div><span style=\"font-size:10pt\">Connecticut Light and Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div><div><a href=\"http:\/\/outage.cl-p.com\/outage\/outagemap.aspx\" target=\"_blank\">http:\/\/outage.cl-p.com\/outage\/outagemap.aspx<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -72.729492, 41.607227, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "National Grid", "Description": "<div><span style=\"font-size:10pt\">National Grid Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div><div><a href=\"https:\/\/s3.amazonaws.com\/stormcenter.nationalgridus.com\/external\/sc_ri.html\" target=\"_blank\">https:\/\/s3.amazonaws.com\/stormcenter.nationalgridus.com\/external\/sc_ri.html<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -71.597900, 42.073761, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "NStar", "Description": "<div><span style=\"font-size:10pt\">NStar Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div><div><a href=\"http:\/\/outage.nstar.com\/outage\/\" target=\"_blank\">http:\/\/outage.nstar.com\/outage\/<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -70.642090, 41.885921, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Met-Ed Regional", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\"><br><\/span><\/div><div dir=\"ltr\"><span style=\"font-size:10pt\">Met-Ed Regional Power Status Maps:<\/span><\/div><div dir=\"ltr\"><a href=\"https:\/\/www.firstenergycorp.com\/content\/customer\/outages_help\/current_outages_maps.html\" style=\"font-size:10pt\" target=\"_blank\">https:\/\/www.firstenergycorp.com\/content\/customer\/outages_help\/current_outages_maps.html<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -78.640137, 40.788860, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "PPL", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\">PPL Power Status Map:<\/span><\/div><div dir=\"ltr\"><a href=\"https:\/\/www.pplelectric.com\/my-account\/outage-center\/outage-map.aspx\" target=\"_blank\">https:\/\/www.pplelectric.com\/my-account\/outage-center\/outage-map.aspx<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -75.739746, 40.763901, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "DTE Energy", "Description": "<div dir=\"ltr\"><span style=\"font-size:10pt\">DTE Energy Power Status Map:<\/span><\/div><div dir=\"ltr\"><a href=\"http:\/\/dteenergy.com\/map\/outage.html\" target=\"_blank\">http:\/\/dteenergy.com\/map\/outage.html<\/a><\/div><div dir=\"ltr\"><span style=\"font-size:10pt\"><br><\/span><\/div><div dir=\"ltr\"><span style=\"font-size:10pt\"><br><\/span><\/div><div dir=\"ltr\">&nbsp;<\/div>" }, "geometry": { "type": "Point", "coordinates": [ -83.710327, 42.256985, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "Central Hudson Gas & Electric", "Description": "<div dir=\"ltr\">Central Hudson Gas &amp; Electric Power Status Map:&nbsp;<\/div><div dir=\"ltr\"><a href=\"http:\/\/stormcentral.cenhud.com\/default.aspx\" target=\"_blank\">http:\/\/stormcentral.cenhud.com\/default.aspx<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -74.014893, 41.816360, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "National Grid", "Description": "<div><span style=\"font-size:10pt\">National Grid Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div><div><a href=\"https:\/\/www1.nationalgridus.com\/PowerOutageMap-NY-RES\" target=\"_blank\">https:\/\/www1.nationalgridus.com\/PowerOutageMap-NY-RES<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -74.981689, 43.810745, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "National Grid", "Description": "<div><span style=\"font-size:10pt\">National Grid Power Status Map:<\/span><span style=\"font-size:10pt\">&nbsp;<\/span><\/div><div><a href=\"https:\/\/www1.nationalgridus.com\/PowerOutageMap-NY-RES\" target=\"_blank\">https:\/\/www1.nationalgridus.com\/PowerOutageMap-NY-RES<\/a><\/div>" }, "geometry": { "type": "Point", "coordinates": [ -79.057617, 42.472095, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "PSE&G", "Description": "<div><font face=\"arial\" size=\"2\">PSE&amp;G Power Status Map:<\/font><\/div><font face=\"arial\" size=\"2\"><a href=\"http:\/\/www.pseg.com\/home\/customer_service\/outage_info\/outagemap.jsp\" target=\"_blank\">http:\/\/www.pseg.com\/home\/customer_service\/outage_info\/outagemap.jsp<\/a><\/font>" }, "geometry": { "type": "Point", "coordinates": [ -74.237366, 40.616035, 0.000000 ] } }
,
{ "type": "Feature", "properties": { "Name": "BGE", "Description": "<div>BGE Power Status Map<\/div><font face=\"arial\" size=\"2\"><a href=\"http:\/\/www.bge.com\/customerservice\/stormsoutages\/currentoutages\/pages\/default.aspx\" target=\"_blank\">http:\/\/www.bge.com\/customerservice\/stormsoutages\/currentoutages\/pages\/default.aspx<\/a><\/font>" }, "geometry": { "type": "Point", "coordinates": [ -76.596680, 39.347042, 0.000000 ] } }

]
}

